import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import { useQuery } from "@tanstack/react-query";
import {
  ReactElement,
  JSXElementConstructor,
  ReactFragment,
  ReactPortal,
} from "react";
import Link from "next/link";
const Home: NextPage = () => {
  const { status, data, isFetching } = GetPost();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {status === "loading" ? (
          <div>로딩 중 입니다.</div>
        ) : status === "error" ? (
          <div>에러입니다</div>
        ) : (
          <>
            {data.map(
              (user: {
                id: string;
                title:
                  | string
                  | number
                  | boolean
                  | ReactElement<any, string | JSXElementConstructor<any>>
                  | ReactFragment
                  | ReactPortal
                  | null
                  | undefined;
                user:
                  | string
                  | number
                  | boolean
                  | ReactElement<any, string | JSXElementConstructor<any>>
                  | ReactFragment
                  | ReactPortal
                  | null
                  | undefined;
              }) => (
                <>
                  <Link href={`news/${user.id}`}>
                    <ul>
                      <li>{user.title}</li>
                      <li>{user.user}</li>
                    </ul>
                  </Link>
                </>
              )
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default Home;
const GetPost = () => {
  return useQuery(["posts"], async () => {
    console.log(process.env.NEXT_PUBLIC_API_NEWS_BASE_URL);
    const { data } = await axios.get(
      process.env.NEXT_PUBLIC_API_NEWS_BASE_URL + "/news/1.json"
    );

    return data;
  });
};
